---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/friends":
    get:
      summary: list friends
      responses:
        '200':
          description: successful
    post:
      summary: create friend
      responses:
        '200':
          description: successful
  "/api/v1/friends/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show friend
      responses:
        '200':
          description: successful
    patch:
      summary: update friend
      responses:
        '200':
          description: successful
    put:
      summary: update friend
      responses:
        '200':
          description: successful
    delete:
      summary: delete friend
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
