# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    adapter: postgresql
    encoding: unicode
    port: <%= ENV["DATABASE_PORT"] || '5432' %>
    host: <%= ENV["DATABASE_HOST"] || 'localhost' %>
    database: <%= ENV["DATABASE_NAME"] || "rails_api_development" %>
    pool: 15
    username: <%= ENV["DATABASE_USR"] %>
    password: <%= ENV["DATABASE_PWD"] %>
    variables:
      statement_timeout: <%= ENV['DATABASE_STATEMENT_TIMEOUT'] || 60 * 1000 %>

  replica:
    adapter: postgresql
    encoding: unicode
    port: <%= ENV["DATABASE_PORT"] || '5432' %>
    host: <%= ENV["DATABASE_HOST"] || 'localhost' %>
    database: <%= ENV["SLAVE_DATABASE_NAME"] || "slave_rails_api_development" %>
    pool: 15
    username: <%= ENV["DATABASE_USR"] %>
    password: <%= ENV["DATABASE_PWD"] %>
    variables:
      statement_timeout: <%= ENV['DATABASE_STATEMENT_TIMEOUT'] || 60 * 1000 %>
    replica: true
    database_tasks: false

test:
  adapter: postgresql
  encoding: unicode
  port: <%= ENV["DATABASE_PORT"] || '5432' %>
  database: rails_api_test
  pool: 25
  host: <%= ENV["DATABASE_HOST"] || 'localhost' %>
  username: <%= ENV["DATABASE_USR"] %>
  password: <%= ENV["DATABASE_PWD"] %>
  variables:
    statement_timeout: <%= ENV['DATABASE_STATEMENT_TIMEOUT'] || 60 * 1000 %>  
